<?php

/**
 * @file
 * Contains menu_image.module.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function menu_image_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the menu_image module.
    case 'help.page.menu_image':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Add image to menu items.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_entity_base_field_info().
 */
function menu_image_entity_base_field_info(EntityTypeInterface $entity_type) {
  $fields = [];

  if ($entity_type->id() === 'menu_link_content') {
    $fields['thumbnail'] = BaseFieldDefinition::create('image')
      ->setLabel(t('Image'))
      ->setDescription(t('Menu item image.'))
      ->setRevisionable(TRUE)
      ->setTranslatable(TRUE)
      ->setDisplayOptions('form', [
        'type' => 'image',
        'weight' => 5,
      ]);

    $ids = [
      'Arbeitsplatz' => 'Arbeitsplatz',
      'RZ' => 'RZ',
      'DB Team' => 'DB Team',
      'Technisches PM' => 'Technisches PM',
      'Das Projekt' => 'Das Projekt',
      'Arbeitsgebiete' => 'Arbeitsgebiete',
      'Infoportal' => 'Infoportal',
      'Tools' => 'Tools'
    ];

    //$ids = "Train\nTarget\nSbahn\nDiagram\nBubbles\nStack";

    $fields['icon'] = BaseFieldDefinition::create('list_string')
      ->setLabel(t('Image ID'))
      ->setDescription(t('ID of predefined image'))
      ->setRevisionable(TRUE)
      ->setTranslatable(TRUE)
      ->setSetting('allowed_values', $ids)
      ->setSetting('multiple_values ', FALSE)
      //->setCardinality(-1)
      ->setDisplayOptions('form', [
        'type' => 'options_select',
        'weight' => 2
      ])
      ->setDisplayConfigurable('form', TRUE);
  }

  return $fields;
}
